# Generated by Django 3.1.1 on 2020-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('song', models.FileField(null=True, upload_to='')),
                ('album', models.ImageField(null=True, upload_to='album/')),
            ],
        ),
    ]
